### PR TITLE
Updating nussl to include deep learning

### LINKED ISSUE #123: Onboarding users new to source separation
Source separation is still a relatively esoteric research field, so it would be nice to have materials for users who have no idea how to use source separation. We should implement this in two ways:

- [ ]  A how-to guide in the documentation that gives a broad overview of algorithms. E.g., "If your signal has X and is Y, try algorithm A, which has such and such assumptions, or algorithm B."  A flow chart would also be nice.

- [ ]  Additionally, docs for individual algorithms should clearly outline the assumptions the algorithms make, and what the strengths and weaknesses are for each algorithm.

### LINKED ISSUE #133: module 'nussl' has no attribute 'AudioSignal'
#### Description

When I import nussl and run:
```python
history = nussl.AudioSignal('HistoryRepeatingPropellerHeads.wav')
```

It gives me the error in the title.

#### Steps/Code to Reproduce

see above

#### Expected Results

No error occurs

#### Actual Results

This output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nussl' has no attribute 'AudioSignal'
```

#### Versions

```
import platform; print(platform.platform())
Darwin-18.2.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.0
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.20.2
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.2
>>> import nussl; print("nussl", nussl.__version__)
```

### PR DESCRIPTION
**Pull request by pseeth**
#### Reference Issue

Fixes #133, #143, #142, #141 #140, #139, #132, #130, #135, #127, #115, #85, #145 

#### What does this implement/fix? Explain your changes.
The most significant contribution in this pull request is the integration of deep learning into nussl. Deep learning is the current state-of-the-art for source separation and it is currently not in nussl. This pull request integrates both training and inference code for three deep learning approaches and is extensibly for many more. It includes Deep Clustering, Mask Inference, and Chimera networks. Along with this, it also fixes a number of issues listed above. Finally, it updates nussl to work with (and only with) Python 3.6 and above. Python 2 is deprecated by the end of the year and Python 3.5 and below are officially in maintenance mode. nussl should work with the latest Python.

### CODE REVIEW

**Comment by pseeth** [comment]
Closing in favor of #148.
